name: user-statistician

on:
  # Run daily at 03:00 UTC
  schedule:
    - cron: '0 3 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Generate user stats image
      - name: Generate the user stats image
        uses: cicirello/user-statistician@v1
        with:
          image-file: "images/userstats-dark.svg"
          include-title: true
          hide-keys: true
          colors: "dracula"
          commit-and-push: true           # Automatically commit back
          category-order: "general, contributions"
          commit-message: "Update GitHub Stats (Automated)"
        env:
          # Safe GitHub token provided by Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
